import fs from 'fs'
import { readdir, readFile, writeFile } from 'fs/promises'
import path from 'path'

type TTokens = 'colors' | 'fontSizes' | 'boxShadows'
const tokens: TTokens[] = ['colors', 'fontSizes', 'boxShadows']

export async function addToTailwindConfig() {
  const rootPath = process.cwd() + '/tailwind.config.js'

  const IS_TAILWIND_BEING_USED = fs.existsSync(rootPath)
  if (!IS_TAILWIND_BEING_USED) return
  const tokenInserts = {
    colors: '\t\t\t\t...mirrorful.Tokens.colors,',
    fontSize: '\t\t\t\t...mirrorful.Tokens.fontSizes,',
    dropShadow: '\t\t\t\t...mirrorful.Tokens.boxShadows,',
  }

  const tailwindInserts = {
    colors: `\t\t\tcolors: {\n${tokenInserts['colors']}\n\t\t\t},`,
    fontSize: `\t\t\tfontSize: {\n${tokenInserts['fontSize']}\n\t\t\t},`,
    dropShadow: `\t\t\tdropShadow: {\n${tokenInserts['dropShadow']}\n\t\t\t},`,
  }

  const [SHOULD_NOT_UPDATE_TAILWIND_CONFIG, tokensUpdateArr] =
    await shouldUpdateTailwindConfig({
      keys: tokens,
      path: rootPath,
    })

  if (SHOULD_NOT_UPDATE_TAILWIND_CONFIG) return

  const mirrorfulFolderPath = await getFolderPath({
    folderName: '.mirrorful',
  })
  if (mirrorfulFolderPath.length < 0) return
  try {
    let tailwindFile = await readFile(rootPath, 'utf8')
    const hasColors = tailwindFile.match(/colors:(\s|^\s)(\{|\n)/)
    const hasFontSizes = tailwindFile.match(/fontSize:(\s|^\s)(\{|\n)/)
    const hasFontWeights = tailwindFile.match(/fontWeight:(\s|^\s)(\{|\n)/)
    const hasDropShadow = tailwindFile.match(/dropShadow:(\s|^\s)(\{|\n)/)

    // opening up extends brackets
    tailwindFile = tailwindFile.replace(/{}/g, '{\n}')

    const tailwindFileArr = tailwindFile.split('\n')

    let extendIndex =
      tailwindFileArr.findIndex((t) => t.includes('extend:')) + 1
    const colorsIndex = hasColors
      ? tailwindFileArr.findIndex((t) => t.includes('colors:')) + 1
      : -1
    let fontSizeIndex = hasFontSizes
      ? tailwindFileArr.findIndex((t) => t.includes('fontSize:')) + 1
      : -1
    const fontWeightIndex = hasFontWeights
      ? tailwindFileArr.findIndex((t) => t.includes('fontWeight:')) + 1
      : -1
    let dropShadowIndex = hasDropShadow
      ? tailwindFileArr.findIndex((t) => t.includes('dropShadow:')) + 1
      : -1

    if (!tokensUpdateArr['colors']) {
      if (hasColors) {
        tailwindFileArr.splice(colorsIndex, 0, tokenInserts['colors'])
        fontSizeIndex++
        dropShadowIndex++
      } else {
        tailwindFileArr.splice(extendIndex, 0, tailwindInserts['colors'])
        extendIndex++
      }
    }

    if (!tokensUpdateArr['fontSizes']) {
      if (hasFontSizes) {
        tailwindFileArr.splice(fontSizeIndex, 0, tokenInserts['fontSize'])
        dropShadowIndex++
      } else {
        tailwindFileArr.splice(extendIndex, 0, tailwindInserts['fontSize'])
        extendIndex++
      }
    }

    if (!tokensUpdateArr['boxShadows']) {
      if (hasDropShadow) {
        tailwindFileArr.splice(dropShadowIndex, 0, tokenInserts['dropShadow'])
      } else {
        tailwindFileArr.splice(extendIndex, 0, tailwindInserts['dropShadow'])
        extendIndex++
      }
    }
    let mirrorfulImport = ''
    if (!tailwindFile.includes('.mirrorful/theme_cjs.js')) {
      mirrorfulImport = `const mirrorful = require('${mirrorfulFolderPath}/theme_cjs.js')\n`
    }
    await writeFile(
      rootPath,
      mirrorfulImport + tailwindFileArr.join('\n'),
      'utf-8'
    )
  } catch (error) {
    console.error(error)
  }
}
/**
 *
 * @param keys The tokens generated by mirrorful
 * @param path The path to the tailwind file
 * @returns Boolean
 */
async function shouldUpdateTailwindConfig({
  keys,
  path,
}: {
  keys: Array<TTokens>
  path: string
}) {
  const tailwindFile = await readFile(path, 'utf-8')
  console.log(tailwindFile)
  const booleanArr: Record<TTokens, boolean> = {
    colors: false,
    boxShadows: false,
    fontSizes: false,
  }

  for (let i = 0; i < keys.length; i++) {
    const regex = `Tokens.${keys[i]}`
    booleanArr[keys[i]] = tailwindFile.includes(regex)
  }
  return [Object.values(booleanArr).every((a) => a), booleanArr] as const
}

const skipDirs = [
  'node_modules',
  '.next',
  '.git',
  '.pnp',
  'coverage',
  'out',
  'build',
  'lib',
  '.vercel',
]
async function getFolderPath({ folderName }: { folderName: string }) {
  const rootDir = process.cwd()
  let finalPath = ''
  const queue = [...(await readdir(rootDir))]
  const visited = []

  while (queue.length > 0) {
    const folder = queue.shift()
    // if the next folder is empty quit
    if (folder === undefined) break
    // skip over the folders that most likely do not contain the folder
    if (skipDirs.includes(folder)) {
      visited.push(folder)
      continue
    }

    // if the path is a folder then check for the name
    if (fs.lstatSync(folder).isDirectory()) {
      if (folder.includes(folderName)) {
        finalPath = folder
        break
      }
      visited.push(folder)
      queue.push(
        ...(await readdir(path.join(rootDir, folder))).map(
          (path) => `${folder}/${path}`
        )
      )
    }
  }

  if (finalPath.length < 0) {
    return ''
  }

  return './' + finalPath
}
