"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MirrorfulApiEnvironment = void 0;
exports.MirrorfulApiEnvironment = {
    Production: "https://mirrorful-server.herokuapp.com/",
    Development: "http://localhost:8080/",
};
