import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mirrorful + Tailwind + Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-4xl font-bold underline">
          Hello world from a Nextjs app with Tailwind!
        </h1>
      </main>
    </>
  )
}
