"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MirrorfulApiClient = void 0;
const Client_1 = require("./api/resources/registry/client/Client");
class MirrorfulApiClient {
    options;
    constructor(options) {
        this.options = options;
    }
    _registry;
    get registry() {
        return (this._registry ??= new Client_1.Registry(this.options));
    }
}
exports.MirrorfulApiClient = MirrorfulApiClient;
