/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const MirrorfulApiEnvironment: {
    readonly Production: "https://mirrorful-server.herokuapp.com/";
    readonly Development: "http://localhost:8080/";
};
export declare type MirrorfulApiEnvironment = typeof MirrorfulApiEnvironment.Production | typeof MirrorfulApiEnvironment.Development;
