import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faBell,
  faCircleCheck,
  faMoon,
} from '@fortawesome/free-solid-svg-icons'
import Head from 'next/head'
import { Container, Button, Row, Col, Spinner, Badge } from 'react-bootstrap'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mirrorful + Bootstrap + Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container style={{ padding: '36px', maxWidth: '780px' }}>
          <Container style={{ padding: '24px' }}>
            <h1 style={{ marginBottom: '24px' }}>
              Mirrorful + Bootstrap + Next Example
            </h1>
            <p
              style={{
                marginBottom: '24px',
                fontSize: 16,
                fontWeight: 'medium',
              }}
            >
              Open your Mirrorful editor (
              <code
                style={{
                  backgroundColor: `var(--color-cool-gray)`,
                  padding: '2.8px',
                  color: 'black',
                }}
              >
                npx mirrorful editor
              </code>
              ) to make live changes!
            </p>
            <Row>
              {['hot-pink', 'lizard-green', 'cool-teal'].map((color) => (
                <Col key={color}>
                  <p>
                    Color Scheme:{' '}
                    <span
                      style={{
                        fontWeight: 'bold',
                        color: `var(--color-${color}-400)`,
                      }}
                    >
                      {color}
                    </span>
                  </p>
                  <Container
                    style={{
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'flex-start',
                    }}
                  >
                    <Button
                      style={{ marginBottom: 8 }}
                      variant={`${color}`}
                      size="lg"
                    >
                      Button
                    </Button>
                    <Spinner
                      style={{
                        color: `var(--color-${color})`,
                        marginBottom: 8,
                      }}
                    />
                    <Badge
                      style={{
                        padding: 12,
                        marginBottom: 8,
                      }}
                      className={`badge-${color}`}
                    >
                      BADGE
                    </Badge>
                  </Container>
                  <Container
                    style={{ display: 'flex', gap: '10px', marginTop: '8px' }}
                  >
                    <FontAwesomeIcon
                      width={16}
                      height={16}
                      color={`var(--color-${color}-400)`}
                      icon={faCircleCheck}
                    />
                    <FontAwesomeIcon
                      width={16}
                      height={16}
                      color={`var(--color-${color}-400)`}
                      icon={faBell}
                    />
                    <FontAwesomeIcon
                      width={16}
                      height={16}
                      color={`var(--color-${color}-400)`}
                      icon={faMoon}
                    />
                  </Container>
                  <Container
                    style={{
                      marginTop: '16px',
                    }}
                  >
                    <code
                      style={{
                        color: `var(--color-${color}-400)`,
                        backgroundColor: `var(--color-cool-gray)`,
                        padding: '2.8px',
                      }}
                    >
                      Code Snippet
                    </code>
                  </Container>
                </Col>
              ))}
            </Row>
          </Container>
        </Container>
      </main>
    </>
  )
}
