/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { MirrorfulApi } from "../../../..";
export declare namespace Registry {
    interface Options {
        environment: string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}
export declare class Registry {
    protected readonly options: Registry.Options;
    constructor(options: Registry.Options);
    getS3UrlForLibraryUpload(orgId: MirrorfulApi.OrgId, libraryId: MirrorfulApi.LibraryId): Promise<MirrorfulApi.S3UrlForLibraryUploadResponse>;
    postS3UrlForLibraryUpload(orgId: MirrorfulApi.OrgId, libraryId: MirrorfulApi.LibraryId): Promise<MirrorfulApi.S3UrlForLibraryUploadResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
