/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { MirrorfulApi } from "../../../..";
export declare namespace Registry {
    interface Options {
        environment?: environments.MirrorfulApiEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}
export declare class Registry {
    protected readonly options: Registry.Options;
    constructor(options: Registry.Options);
    createLibrary(orgId: MirrorfulApi.OrgId, request: MirrorfulApi.CreateLibraryRequest): Promise<MirrorfulApi.CreateLibraryResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
