"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MirrorfulApiTimeoutError = void 0;
class MirrorfulApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, MirrorfulApiTimeoutError.prototype);
    }
}
exports.MirrorfulApiTimeoutError = MirrorfulApiTimeoutError;
