'use strict'
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true })
exports.MirrorfulApiError = void 0
class MirrorfulApiError extends Error {
  statusCode
  body
  constructor({ message, statusCode, body }) {
    super(message)
    Object.setPrototypeOf(this, MirrorfulApiError.prototype)
    if (statusCode != null) {
      this.statusCode = statusCode
    }
    if (body !== undefined) {
      this.body = body
    }
  }
}
exports.MirrorfulApiError = MirrorfulApiError
