name: Core - Build, Lint, Test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/core/**'
  push:
    branches:
      - main
    paths:
      - 'packages/core/**'

jobs:
  build:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: install # will run `yarn install` command in packages/core

      - name: build packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: build # will run `yarn build` command in packages/core

      - name: test packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: test

      - name: lint packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: lint
